import { drizzle } from 'drizzle-orm/node-postgres';
import { Pool } from 'pg';
import { sql, eq } from 'drizzle-orm';
import { readFileSync } from 'fs';
import { resolve } from 'path';
import bcrypt from 'bcryptjs';
import * as schema from './schema';

// Load .env.local
try {
  const envPath = resolve(process.cwd(), '.env.local');
  const envContent = readFileSync(envPath, 'utf-8');
  for (const line of envContent.split('\n')) {
    const match = line.match(/^([^#=]+)=(.*)$/);
    if (match) {
      const key = match[1].trim();
      const value = match[2].trim().replace(/^["']|["']$/g, '');
      if (!process.env[key]) {
        process.env[key] = value;
      }
    }
  }
} catch {
  // .env.local not found
}

const SEED_VERSION = 'v2_lesson_content';

async function seed() {
  const pool = new Pool({ connectionString: process.env.DATABASE_URL });
  const db = drizzle(pool, { schema });

  try {
    await db.execute(sql`
      CREATE TABLE IF NOT EXISTS _seed_log (
        id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        seed_version text NOT NULL UNIQUE,
        applied_at timestamp DEFAULT now()
      )
    `);

    const existing = await db
      .select()
      .from(schema.seedLog)
      .where(eq(schema.seedLog.seedVersion, SEED_VERSION))
      .limit(1);

    if (existing.length > 0) {
      console.log(`Seed "${SEED_VERSION}" already applied. Skipping.`);
      return;
    }

    await db.transaction(async (tx) => {
      // ─── USERS ──────────────────────────────────────────────
      const passwordHash = await bcrypt.hash(
        process.env.SEED_ADMIN_PASSWORD || 'changeme',
        10,
      );
      const studentHash = await bcrypt.hash('student123', 10);

      const [adminUser] = await tx
        .insert(schema.users)
        .values({
          username: 'admin',
          email: 'admin@example.com',
          passwordHash,
          role: 'TEACHER',
          displayName: 'Admin User',
        })
        .returning();

      const [student1] = await tx
        .insert(schema.users)
        .values({
          username: 'student1',
          email: 'student1@example.com',
          passwordHash: studentHash,
          role: 'STUDENT',
          displayName: 'Alice Chen',
        })
        .returning();

      const [student2] = await tx
        .insert(schema.users)
        .values({
          username: 'student2',
          email: 'student2@example.com',
          passwordHash: studentHash,
          role: 'STUDENT',
          displayName: 'Bob Kumar',
        })
        .returning();

      await tx
        .insert(schema.users)
        .values({
          username: 'student3',
          email: 'student3@example.com',
          passwordHash: studentHash,
          role: 'STUDENT',
          displayName: 'Carol Park',
        })
        .returning();

      // ─── QUIZ: Pre-Test (10 MCQ) ───────────────────────────
      const [preTestQuiz] = await tx
        .insert(schema.quizzes)
        .values({
          storageKey: 'pre_test_quiz',
          title: 'Foundations of AI in Software Engineering',
          description:
            'Pre-test quiz covering foundational concepts of AI in software engineering',
          quizType: 'multiple_choice',
        })
        .returning();

      const quizQuestions = [
        {
          storageKey: 'pre_q1',
          questionText:
            'What percentage of code in 2025 will be auto-generated according to Gartner?',
          questionOrder: 1,
          questionType: 'multiple_choice',
          explanation:
            'Gartner projected that by 2025, 50% of code would be auto-generated by AI tools.',
          answers: [
            { answerText: '10%', isCorrect: false, answerOrder: 1 },
            { answerText: '30%', isCorrect: false, answerOrder: 2 },
            { answerText: '50%', isCorrect: true, answerOrder: 3 },
            { answerText: '80%', isCorrect: false, answerOrder: 4 },
          ],
        },
        {
          storageKey: 'pre_q2',
          questionText:
            'Which of the following is an AI-powered code assistant?',
          questionOrder: 2,
          questionType: 'multiple_choice',
          explanation:
            'GitHub Copilot is the AI-powered code assistant among these options.',
          answers: [
            { answerText: 'Notepad++', isCorrect: false, answerOrder: 1 },
            { answerText: 'GitHub Copilot', isCorrect: true, answerOrder: 2 },
            { answerText: 'Microsoft Word', isCorrect: false, answerOrder: 3 },
            {
              answerText: 'Adobe Photoshop',
              isCorrect: false,
              answerOrder: 4,
            },
          ],
        },
        {
          storageKey: 'pre_q3',
          questionText:
            'What was the reported productivity increase in the 2023 Microsoft study on Copilot users?',
          questionOrder: 3,
          questionType: 'multiple_choice',
          explanation:
            'The 2023 Microsoft study found a 55% productivity increase among Copilot users.',
          answers: [
            { answerText: '25%', isCorrect: false, answerOrder: 1 },
            { answerText: '40%', isCorrect: false, answerOrder: 2 },
            { answerText: '55%', isCorrect: true, answerOrder: 3 },
            { answerText: '70%', isCorrect: false, answerOrder: 4 },
          ],
        },
        {
          storageKey: 'pre_q4',
          questionText:
            'Which ethical concern is most associated with AI-generated code?',
          questionOrder: 4,
          questionType: 'multiple_choice',
          explanation:
            'Bias in training data is the primary ethical concern for AI-generated code.',
          answers: [
            { answerText: 'Code efficiency', isCorrect: false, answerOrder: 1 },
            {
              answerText: 'Bias in training data',
              isCorrect: true,
              answerOrder: 2,
            },
            {
              answerText: 'Color scheme choices',
              isCorrect: false,
              answerOrder: 3,
            },
            {
              answerText: 'File naming conventions',
              isCorrect: false,
              answerOrder: 4,
            },
          ],
        },
        {
          storageKey: 'pre_q5',
          questionText:
            "What is the primary function of IBM's AI Fairness 360 toolkit?",
          questionOrder: 5,
          questionType: 'multiple_choice',
          explanation:
            "IBM's AI Fairness 360 is designed to detect and mitigate bias in AI systems.",
          answers: [
            {
              answerText: 'Code compilation',
              isCorrect: false,
              answerOrder: 1,
            },
            {
              answerText: 'Detecting and mitigating bias',
              isCorrect: true,
              answerOrder: 2,
            },
            {
              answerText: 'Database management',
              isCorrect: false,
              answerOrder: 3,
            },
            { answerText: 'UI design', isCorrect: false, answerOrder: 4 },
          ],
        },
        {
          storageKey: 'pre_q6',
          questionText:
            'Which software engineering principle remains unchanged despite AI tools?',
          questionOrder: 6,
          questionType: 'multiple_choice',
          explanation:
            'Understanding user requirements remains a fundamentally human skill that AI cannot replace.',
          answers: [
            {
              answerText: 'Manual syntax checking',
              isCorrect: false,
              answerOrder: 1,
            },
            {
              answerText: 'Understanding user requirements',
              isCorrect: true,
              answerOrder: 2,
            },
            {
              answerText: 'Hand-writing boilerplate',
              isCorrect: false,
              answerOrder: 3,
            },
            {
              answerText: 'Memorizing API syntax',
              isCorrect: false,
              answerOrder: 4,
            },
          ],
        },
        {
          storageKey: 'pre_q7',
          questionText:
            'What is a potential risk of over-reliance on AI coding tools?',
          questionOrder: 7,
          questionType: 'multiple_choice',
          explanation:
            'Over-reliance on AI tools can lead to reduced critical thinking.',
          answers: [
            {
              answerText: 'Faster compilation',
              isCorrect: false,
              answerOrder: 1,
            },
            {
              answerText: 'Reduced critical thinking',
              isCorrect: true,
              answerOrder: 2,
            },
            {
              answerText: 'Better documentation',
              isCorrect: false,
              answerOrder: 3,
            },
            {
              answerText: 'Improved testing',
              isCorrect: false,
              answerOrder: 4,
            },
          ],
        },
        {
          storageKey: 'pre_q8',
          questionText:
            'In the AI-assisted workflow, what role does the developer primarily play?',
          questionOrder: 8,
          questionType: 'multiple_choice',
          explanation:
            'In AI-assisted workflows, developers primarily review and guide AI-generated code.',
          answers: [
            {
              answerText: 'Typing all code manually',
              isCorrect: false,
              answerOrder: 1,
            },
            {
              answerText: 'Reviewing and guiding AI-generated code',
              isCorrect: true,
              answerOrder: 2,
            },
            {
              answerText: 'Avoiding all coding',
              isCorrect: false,
              answerOrder: 3,
            },
            {
              answerText: 'Only writing documentation',
              isCorrect: false,
              answerOrder: 4,
            },
          ],
        },
        {
          storageKey: 'pre_q9',
          questionText:
            'What does "democratization of software engineering" mean in the context of AI?',
          questionOrder: 9,
          questionType: 'multiple_choice',
          explanation:
            'Democratization means making coding accessible to more people through AI assistance.',
          answers: [
            {
              answerText: 'Only experts can code',
              isCorrect: false,
              answerOrder: 1,
            },
            {
              answerText: 'Making coding accessible to more people',
              isCorrect: true,
              answerOrder: 2,
            },
            {
              answerText: 'Eliminating all programmers',
              isCorrect: false,
              answerOrder: 3,
            },
            {
              answerText: 'Increasing software costs',
              isCorrect: false,
              answerOrder: 4,
            },
          ],
        },
        {
          storageKey: 'pre_q10',
          questionText:
            'Which of the following best describes the relationship between AI and software engineers?',
          questionOrder: 10,
          questionType: 'multiple_choice',
          explanation:
            'AI augments software engineers by enhancing their capabilities, not replacing them.',
          answers: [
            { answerText: 'Replacement', isCorrect: false, answerOrder: 1 },
            { answerText: 'Competition', isCorrect: false, answerOrder: 2 },
            { answerText: 'Augmentation', isCorrect: true, answerOrder: 3 },
            { answerText: 'Elimination', isCorrect: false, answerOrder: 4 },
          ],
        },
      ];

      for (const q of quizQuestions) {
        const [insertedQuestion] = await tx
          .insert(schema.questions)
          .values({
            quizId: preTestQuiz.id,
            storageKey: q.storageKey,
            questionText: q.questionText,
            questionOrder: q.questionOrder,
            questionType: q.questionType,
            explanation: q.explanation,
          })
          .returning();

        for (const a of q.answers) {
          await tx.insert(schema.answers).values({
            questionId: insertedQuestion.id,
            answerText: a.answerText,
            isCorrect: a.isCorrect,
            answerOrder: a.answerOrder,
          });
        }
      }

      // ─── DISCUSSIONS ────────────────────────────────────────
      const [guidingQuestionsDiscussion] = await tx
        .insert(schema.discussions)
        .values({
          storageKey: 'guiding_questions',
          title: 'Guiding Questions: AI and the Future of Software Engineering',
          description:
            'Discuss how AI might change the role of software engineers and the potential risks of over-reliance on AI tools.',
          createdBy: adminUser.id,
          isPinned: true,
        })
        .returning();

      await tx.insert(schema.discussionPosts).values({
        discussionId: guidingQuestionsDiscussion.id,
        authorId: adminUser.id,
        content:
          "Welcome! Please share your thoughts on these two guiding questions:\n\n1. How might AI change the role of software engineers in 10 years?\n2. What are potential risks of over-reliance on AI tools?\n\nFeel free to respond to each other's ideas.",
      });

      const [debateDiscussion] = await tx
        .insert(schema.discussions)
        .values({
          storageKey: 'debate_democratization',
          title: 'Debate: Will AI democratize software engineering by 2027?',
          description:
            'Randomly assigned pro/con positions. Argue whether AI will make software engineering accessible to everyone.',
          createdBy: adminUser.id,
        })
        .returning();

      await tx.insert(schema.discussionPosts).values({
        discussionId: debateDiscussion.id,
        authorId: adminUser.id,
        content:
          "This thread is for the debate activity. If assigned PRO, argue that AI will democratize software engineering by 2027. If assigned CON, argue why it won't. Remember to support your position with evidence.",
      });

      // ─── CONCEPT CHECKS ─────────────────────────────────────
      await tx.insert(schema.conceptChecks).values([
        {
          storageKey: 'check_ilos',
          title: 'Understanding the ILOs',
          prompt:
            'Do you feel confident you can explain the four learning outcomes to a peer?',
          checkType: 'thumbs',
          sectionKey: 'ilos',
        },
        {
          storageKey: 'check_mod1',
          title: 'Foundations Check',
          prompt:
            'Rate your understanding of traditional vs AI-powered development workflows.',
          checkType: 'scale',
          sectionKey: 'activities',
        },
        {
          storageKey: 'check_mod3',
          title: 'Critical Analysis Check',
          prompt:
            'Can you identify at least one ethical risk of AI-generated code?',
          checkType: 'thumbs',
          sectionKey: 'activities',
        },
        {
          storageKey: 'check_synthesis',
          title: 'Lesson Synthesis',
          prompt:
            "What surprised you most about AI's capabilities? Write a brief reflection.",
          checkType: 'text',
          sectionKey: 'synthesis',
        },
      ]);

      // ─── SLIDES (10 slides) ─────────────────────────────────
      await tx.insert(schema.slides).values([
        {
          storageKey: 'slide_01',
          slideOrder: 1,
          title: 'AI-Powered Software Engineering',
          content:
            'From Manual Coding to Intelligent Workflows\nUniversity Year 1 | Interactive Lesson Plan',
          slideType: 'title',
        },
        {
          storageKey: 'slide_02',
          slideOrder: 2,
          title: 'Learning Outcomes (ILOs)',
          content:
            'By the end of this lesson, you will be able to:\n- Analyze the evolution of software engineering from manual to AI-powered workflows\n- Apply AI-assisted development tools to solve basic coding challenges\n- Evaluate ethical considerations and technical limitations of AI\n- Create a documented prototype using AI-generated code with iterative refinement',
          slideType: 'content',
        },
        {
          storageKey: 'slide_03',
          slideOrder: 3,
          title: 'Pre-Class Preparation',
          content:
            'Before the lesson:\n- Watch: "How AI is reshaping programming" (TED-Ed, 10 min)\n- Read: IEEE Spectrum article on AI\'s impact on coding accessibility\n- Complete: 5-question pre-test quiz on Canvas\n- Think about: How might AI change software engineering in 10 years?',
          slideType: 'content',
        },
        {
          storageKey: 'slide_04',
          slideOrder: 4,
          title: 'Introduction (20 min)',
          content:
            '- Hook: Live demo of GitHub Copilot writing a sorting algorithm\n- Poll: "How many of you have used AI code assistants?"\n- Discussion: AI replaces coders vs. AI augments productivity',
          slideType: 'activity',
        },
        {
          storageKey: 'slide_05',
          slideOrder: 5,
          title: 'Mod 1: Foundations of AI Development (30 min)',
          content:
            '- Interactive lecture: Map traditional vs AI-powered workflow terms\n- Case Study: 2023 Microsoft study - 55% productivity increase\n- Think-Pair-Share: What software engineering principles remain unchanged?',
          slideType: 'content',
        },
        {
          storageKey: 'slide_06',
          slideOrder: 6,
          title: 'Mod 2: Hands-On Practice (60 min)',
          content:
            'Live Coding Workshop (pairs):\n- Challenge 1: Generate basic API with OpenAPI and AI comments\n- Challenge 2: Implement a CRUD system with minimal human input\n- Peer Teaching: 5-min speed presentations on unique AI tools',
          slideType: 'activity',
        },
        {
          storageKey: 'slide_07',
          slideOrder: 7,
          title: 'Mod 3: Critical Analysis (40 min)',
          content:
            '- Debate: "AI will democratize software engineering by 2027"\n- Ethical Exercise: Identify bias using IBM AI Fairness 360\n- Poll: "Should AI-assisted coding exams count as independent work?"',
          slideType: 'activity',
        },
        {
          storageKey: 'slide_08',
          slideOrder: 8,
          title: 'Synthesis & Closure (30 min)',
          content:
            '- Post-Test: Compare with pre-test results\n- One-Minute Paper: "What surprised you most?"\n- Preview: Next module on prompt engineering for developers',
          slideType: 'content',
        },
        {
          storageKey: 'slide_09',
          slideOrder: 9,
          title: 'Assessment Overview',
          content:
            'Formative:\n- Real-time polling responses\n- Workshop rubric for code quality\n- Exit ticket self-assessment\n\nSummative - Prototype Presentation (20%):\n- Technical accuracy (40%)\n- Critical reflection (30%)\n- Human-AI collaboration (30%)',
          slideType: 'assessment',
        },
        {
          storageKey: 'slide_10',
          slideOrder: 10,
          title: 'Key Takeaways',
          content:
            '- AI augments, not replaces, software engineers\n- Understanding requirements and critical thinking remain essential\n- Ethical awareness is crucial when using AI tools\n- Iterative refinement of AI-generated code is the key skill\n\nNext: Prompt Engineering for Developers',
          slideType: 'content',
        },
      ]);

      // ─── STUDENT PROGRESS (sample) ──────────────────────────
      await tx.insert(schema.studentProgress).values([
        {
          userId: student1.id,
          sectionKey: 'ilos',
          completed: true,
        },
        {
          userId: student1.id,
          sectionKey: 'preclass',
          completed: true,
        },
        {
          userId: student1.id,
          sectionKey: 'introduction',
          completed: true,
        },
        {
          userId: student2.id,
          sectionKey: 'ilos',
          completed: true,
        },
        {
          userId: student2.id,
          sectionKey: 'preclass',
          completed: true,
        },
      ]);

      // ─── SEED LOG ───────────────────────────────────────────
      await tx.insert(schema.seedLog).values({
        seedVersion: SEED_VERSION,
      });
    });

    console.log(`Seed "${SEED_VERSION}" applied successfully.`);
  } catch (error) {
    console.error('Seeding failed:', error);
    throw error;
  } finally {
    await pool.end();
  }
}

seed()
  .then(() => process.exit(0))
  .catch(() => process.exit(1));
