import { drizzle } from 'drizzle-orm/postgres-js';
import postgres from 'postgres';
import { sql, eq } from 'drizzle-orm';
import bcrypt from 'bcryptjs';
import * as schema from './schema';

// --- Seed versions ---
const V1_SEED_VERSION = 'v1_initial';
const V2_SEED_VERSION = 'v2_lesson_data';

// --- Ensure _seed_log table exists ---
async function ensureSeedLogTable(db: ReturnType<typeof drizzle>) {
  await db.execute(sql`
    CREATE TABLE IF NOT EXISTS _seed_log (
      id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      seed_version text NOT NULL UNIQUE,
      applied_at timestamp DEFAULT now()
    )
  `);
}

// --- Check if a seed version has already been applied ---
async function isSeedApplied(
  db: ReturnType<typeof drizzle>,
  version: string,
): Promise<boolean> {
  const existing = await db
    .select()
    .from(schema.seedLog)
    .where(eq(schema.seedLog.seedVersion, version))
    .limit(1);
  return existing.length > 0;
}

// --- v1_initial: Create admin user ---
async function seedV1(db: ReturnType<typeof drizzle>) {
  if (await isSeedApplied(db, V1_SEED_VERSION)) {
    console.log(`Seed "${V1_SEED_VERSION}" already applied. Skipping.`);
    return;
  }

  await db.transaction(async (tx) => {
    const passwordHash = await bcrypt.hash(
      process.env.SEED_ADMIN_PASSWORD || 'changeme',
      10,
    );

    await tx.insert(schema.users).values({
      username: 'admin',
      email: 'admin@example.com',
      passwordHash,
      role: 'TEACHER',
      displayName: 'Admin User',
    });

    await tx.insert(schema.seedLog).values({
      seedVersion: V1_SEED_VERSION,
    });
  });

  console.log(`Seed "${V1_SEED_VERSION}" applied successfully.`);
}

// --- v2_lesson_data: Create lesson content ---
async function seedV2(db: ReturnType<typeof drizzle>) {
  if (await isSeedApplied(db, V2_SEED_VERSION)) {
    console.log(`Seed "${V2_SEED_VERSION}" already applied. Skipping.`);
    return;
  }

  // Get admin user for discussion createdBy
  const adminUser = await db
    .select()
    .from(schema.users)
    .where(eq(schema.users.username, 'admin'))
    .limit(1);

  if (adminUser.length === 0) {
    throw new Error('Admin user not found. Please run v1_initial seed first.');
  }

  const adminId = adminUser[0].id;

  await db.transaction(async (tx) => {
    // ---- Quizzes ----
    const [quiz1] = await tx
      .insert(schema.quizzes)
      .values({
        storageKey: 'quiz:pre-test',
        title: 'Pre-Test: Hong Kong EFL Curriculum',
        description:
          "Assess your prior knowledge of Hong Kong's EFL curriculum framework",
        quizType: 'mixed',
      })
      .returning({ id: schema.quizzes.id });

    const [quiz2] = await tx
      .insert(schema.quizzes)
      .values({
        storageKey: 'quiz:formative',
        title: 'Formative Assessment: CLIL Implementation',
        description:
          'Quick check on your understanding of CLIL challenges and curriculum alignment',
        quizType: 'mixed',
      })
      .returning({ id: schema.quizzes.id });

    // ---- Questions for Quiz 1 (Pre-Test) ----
    const [q1_1] = await tx
      .insert(schema.questions)
      .values({
        quizId: quiz1.id,
        storageKey: 'q:pretest-1',
        questionText:
          "Which of the following best represents Hong Kong's biliteracy goal?",
        questionOrder: 0,
        questionType: 'multiple_choice',
        explanation:
          "Hong Kong's biliteracy policy focuses on written Chinese and written English, while trilingualism covers Cantonese, Mandarin, and spoken English.",
      })
      .returning({ id: schema.questions.id });

    await tx.insert(schema.answers).values([
      {
        questionId: q1_1.id,
        answerText: 'Proficiency in English and Mandarin',
        isCorrect: false,
        answerOrder: 0,
      },
      {
        questionId: q1_1.id,
        answerText: 'Proficiency in Cantonese and English',
        isCorrect: true,
        answerOrder: 1,
      },
      {
        questionId: q1_1.id,
        answerText: 'Mastery of academic writing in English',
        isCorrect: false,
        answerOrder: 2,
      },
      {
        questionId: q1_1.id,
        answerText: 'Proficiency in all three official languages',
        isCorrect: false,
        answerOrder: 3,
      },
    ]);

    const [q1_2] = await tx
      .insert(schema.questions)
      .values({
        quizId: quiz1.id,
        storageKey: 'q:pretest-2',
        questionText: 'What does CLIL stand for?',
        questionOrder: 1,
        questionType: 'multiple_choice',
        explanation:
          'CLIL stands for Content and Language Integrated Learning, an approach where subject content is taught through a foreign language.',
      })
      .returning({ id: schema.questions.id });

    await tx.insert(schema.answers).values([
      {
        questionId: q1_2.id,
        answerText: 'Content and Language Integrated Learning',
        isCorrect: true,
        answerOrder: 0,
      },
      {
        questionId: q1_2.id,
        answerText: 'Curriculum and Language Inclusive Learning',
        isCorrect: false,
        answerOrder: 1,
      },
      {
        questionId: q1_2.id,
        answerText: 'Content and Literacy Integrated Learning',
        isCorrect: false,
        answerOrder: 2,
      },
      {
        questionId: q1_2.id,
        answerText: 'Classroom Language Instructional Learning',
        isCorrect: false,
        answerOrder: 3,
      },
    ]);

    const [q1_3] = await tx
      .insert(schema.questions)
      .values({
        quizId: quiz1.id,
        storageKey: 'q:pretest-3',
        questionText:
          "Hong Kong's biliteracy policy refers to proficiency in English and Mandarin only.",
        questionOrder: 2,
        questionType: 'true_false',
        explanation:
          'Biliteracy in Hong Kong refers to proficiency in written Chinese and written English, not Mandarin. Trilingualism covers Cantonese, Mandarin, and spoken English.',
      })
      .returning({ id: schema.questions.id });

    await tx.insert(schema.answers).values([
      {
        questionId: q1_3.id,
        answerText: 'True',
        isCorrect: false,
        answerOrder: 0,
      },
      {
        questionId: q1_3.id,
        answerText: 'False',
        isCorrect: true,
        answerOrder: 1,
      },
    ]);

    const [q1_4] = await tx
      .insert(schema.questions)
      .values({
        quizId: quiz1.id,
        storageKey: 'q:pretest-4',
        questionText:
          'Which of the following is NOT one of the key strands in the HK EFL curriculum framework?',
        questionOrder: 3,
        questionType: 'multiple_choice',
        explanation:
          'The HK EFL curriculum framework includes Interpersonal, Knowledge, and Experience as key strands. Translation is not a separate strand.',
      })
      .returning({ id: schema.questions.id });

    await tx.insert(schema.answers).values([
      {
        questionId: q1_4.id,
        answerText: 'Interpersonal',
        isCorrect: false,
        answerOrder: 0,
      },
      {
        questionId: q1_4.id,
        answerText: 'Knowledge',
        isCorrect: false,
        answerOrder: 1,
      },
      {
        questionId: q1_4.id,
        answerText: 'Experience',
        isCorrect: false,
        answerOrder: 2,
      },
      {
        questionId: q1_4.id,
        answerText: 'Translation',
        isCorrect: true,
        answerOrder: 3,
      },
    ]);

    const [q1_5] = await tx
      .insert(schema.questions)
      .values({
        quizId: quiz1.id,
        storageKey: 'q:pretest-5',
        questionText:
          "Explain the challenges of implementing CLIL in Hong Kong's multilingual environment.",
        questionOrder: 4,
        questionType: 'short_answer',
        explanation:
          'Consider the interplay between Cantonese, Mandarin, and English in content instruction, teacher training needs, and resource allocation.',
      })
      .returning({ id: schema.questions.id });

    await tx.insert(schema.answers).values([
      {
        questionId: q1_5.id,
        answerText: 'Sample answer',
        isCorrect: true,
        answerOrder: 0,
      },
    ]);

    // ---- Questions for Quiz 2 (Formative Assessment) ----
    const [q2_1] = await tx
      .insert(schema.questions)
      .values({
        quizId: quiz2.id,
        storageKey: 'q:formative-1',
        questionText:
          'Identify 2 challenges in implementing CLIL in Hong Kong',
        questionOrder: 0,
        questionType: 'short_answer',
        explanation:
          'Challenges may include teacher training, resource availability, language proficiency requirements, and balancing content with language objectives.',
      })
      .returning({ id: schema.questions.id });

    await tx.insert(schema.answers).values([
      {
        questionId: q2_1.id,
        answerText: 'Sample answer',
        isCorrect: true,
        answerOrder: 0,
      },
    ]);

    const [q2_2] = await tx
      .insert(schema.questions)
      .values({
        quizId: quiz2.id,
        storageKey: 'q:formative-2',
        questionText:
          "Which assessment method best aligns with the learning outcome 'Adapt standards to diverse contexts'?",
        questionOrder: 1,
        questionType: 'multiple_choice',
        explanation:
          "Concept mapping requires students to actively organize and adapt knowledge, aligning with the 'Create' level of Bloom's taxonomy.",
      })
      .returning({ id: schema.questions.id });

    await tx.insert(schema.answers).values([
      {
        questionId: q2_2.id,
        answerText: 'Multiple-choice exam',
        isCorrect: false,
        answerOrder: 0,
      },
      {
        questionId: q2_2.id,
        answerText: 'Concept map creation',
        isCorrect: true,
        answerOrder: 1,
      },
      {
        questionId: q2_2.id,
        answerText: 'Oral recitation',
        isCorrect: false,
        answerOrder: 2,
      },
      {
        questionId: q2_2.id,
        answerText: 'True/False quiz',
        isCorrect: false,
        answerOrder: 3,
      },
    ]);

    const [q2_3] = await tx
      .insert(schema.questions)
      .values({
        quizId: quiz2.id,
        storageKey: 'q:formative-3',
        questionText:
          "The three-year flexible timeframe allows schools to adjust the pace of curriculum delivery.",
        questionOrder: 2,
        questionType: 'true_false',
        explanation:
          'The three-year flexible timeframe is designed to give schools flexibility in implementing the senior secondary curriculum.',
      })
      .returning({ id: schema.questions.id });

    await tx.insert(schema.answers).values([
      {
        questionId: q2_3.id,
        answerText: 'True',
        isCorrect: true,
        answerOrder: 0,
      },
      {
        questionId: q2_3.id,
        answerText: 'False',
        isCorrect: false,
        answerOrder: 1,
      },
    ]);

    // ---- Discussions ----
    await tx.insert(schema.discussions).values([
      {
        storageKey: 'discussion:interplay',
        title: 'How does the Hong Kong curriculum address the interplay between English and local languages?',
        description:
          'Share your thoughts on how the HK EFL curriculum framework manages the relationship between English and local languages (Cantonese, Mandarin).',
        createdBy: adminId,
        isPinned: false,
      },
      {
        storageKey: 'discussion:flexible-timeframe',
        title: "What are the implications of the 'three-year flexible timeframe' for EFL syllabus design?",
        description:
          'Discuss how the flexible timeframe policy impacts the way schools design and implement their EFL programs.',
        createdBy: adminId,
        isPinned: false,
      },
      {
        storageKey: 'discussion:reflection',
        title: "How might Hong Kong's curriculum approach influence our own teaching context?",
        description:
          "Reflect on how the principles and strategies from HK's EFL curriculum could be applied or adapted to your own educational setting.",
        createdBy: adminId,
        isPinned: false,
      },
    ]);

    // ---- Concept Checks ----
    await tx.insert(schema.conceptChecks).values([
      {
        storageKey: 'cc:ilos',
        title: 'Understanding Learning Outcomes',
        prompt: 'Do you understand the intended learning outcomes for this lesson?',
        checkType: 'thumbs',
        sectionKey: 'ilos',
      },
      {
        storageKey: 'cc:preclass',
        title: 'Pre-Class Preparation',
        prompt: 'Have you completed the pre-class reading and pre-test?',
        checkType: 'thumbs',
        sectionKey: 'preclass',
      },
      {
        storageKey: 'cc:activities',
        title: 'Activity Confidence',
        prompt:
          'How confident are you in facilitating the jigsaw and problem-solving activities?',
        checkType: 'scale',
        sectionKey: 'activities',
      },
      {
        storageKey: 'cc:assessment',
        title: 'Assessment Understanding',
        prompt:
          'Can you distinguish between formative and summative assessments in this lesson?',
        checkType: 'thumbs',
        sectionKey: 'assessment',
      },
      {
        storageKey: 'cc:alignment',
        title: 'Alignment Reflection',
        prompt:
          'Describe one way the assessment methods align with the learning outcomes.',
        checkType: 'text',
        sectionKey: 'alignment',
      },
      {
        storageKey: 'cc:resources',
        title: 'Technology Readiness',
        prompt:
          'Are you familiar with the required technology tools for this lesson?',
        checkType: 'thumbs',
        sectionKey: 'resources',
      },
      {
        storageKey: 'cc:differentiation',
        title: 'Differentiation Strategies',
        prompt:
          'Can you identify at least 2 differentiation strategies from this lesson?',
        checkType: 'thumbs',
        sectionKey: 'differentiation',
      },
      {
        storageKey: 'cc:reflection',
        title: 'Lesson Improvement',
        prompt:
          'What is one improvement you would suggest for this lesson plan?',
        checkType: 'text',
        sectionKey: 'reflection',
      },
    ]);

    // ---- Slides ----
    await tx.insert(schema.slides).values([
      {
        storageKey: 'slide:title',
        slideOrder: 1,
        title: 'Hong Kong EFL Curriculum Framework',
        content:
          'Understanding the Hong Kong EFL Curriculum\nBiliteracy-Trilingualism Policy & CLIL Approaches\n\nA comprehensive lesson for university-level education students',
        slideType: 'title',
        backgroundColor: null,
      },
      {
        storageKey: 'slide:ilos',
        slideOrder: 2,
        title: 'Intended Learning Outcomes',
        content:
          "By the end of this lesson, students will be able to:\n\n- Analyze key components of the HK EFL curriculum framework (Bloom's: Analyze)\n- Evaluate pedagogical strategies aligned with biliteracy-trilingualism policy (Bloom's: Evaluate)\n- Adapt curriculum standards to context-specific lesson planning (Bloom's: Create)\n- Critically reflect on CLIL integration approaches (Bloom's: Analyze/Evaluate)",
        slideType: 'content',
        backgroundColor: null,
      },
      {
        storageKey: 'slide:preclass',
        slideOrder: 3,
        title: 'Pre-Class Preparation',
        content:
          'Pre-Reading:\n- HKEB English Language Curriculum Guide (2020), pp.12-25\n- Video: CLIL Strategies in Hong Kong Schools\n\nPre-Test:\n- 5 questions on biliteracy policy and CLIL\n\nGuiding Questions:\n- How does the HK curriculum address English and local language interplay?\n- What are the implications of the three-year flexible timeframe?',
        slideType: 'content',
        backgroundColor: null,
      },
      {
        storageKey: 'slide:introduction',
        slideOrder: 4,
        title: 'Introduction Activities (12 min)',
        content:
          'Hook:\nAnalyze the headline: "Is Hong Kong\'s English curriculum failing native speakers?"\n\nPre-Test Discussion:\nWord cloud visualization (Mentimeter) comparing class responses\nHighlighting misconceptions: biliteracy vs bilingualism\n\nReal-World Connection:\nHKET 2023 data on declining secondary-level EFL performance',
        slideType: 'activity',
        backgroundColor: null,
      },
      {
        storageKey: 'slide:jigsaw',
        slideOrder: 5,
        title: 'Jigsaw & Problem-Solving (35 min)',
        content:
          'Jigsaw Groups (15 min):\n- Group 1: Biliteracy Policy\n- Group 2: CLIL Implementation\n- Group 3: Four Key Strands Framework\n- Group 4: Assessment Literacy (HKDSE)\n- Group 5: Technology Integration (EdCity)\n\nCase Study (20 min):\nMock school budget proposal meeting curriculum requirements\nPandemic-era constraints\nCLIL integration example in Primary Science',
        slideType: 'activity',
        backgroundColor: null,
      },
      {
        storageKey: 'slide:peerteaching',
        slideOrder: 6,
        title: 'Peer Teaching & Concept Mapping (22 min)',
        content:
          'Peer Teaching Rounds (12 min):\n3-minute TED-style presentations\nCanva templates provided\nCross-group feedback criteria: Clarity & Feasibility\n\nConcept Mapping Challenge (10 min):\nCollaborative concept map on Padlet\nExample: Policy → Strategy → Assessment\n\nFormative Assessment (5 min):\nLightning quiz on CLIL challenges\n\nBreak (5 min)',
        slideType: 'activity',
        backgroundColor: null,
      },
      {
        storageKey: 'slide:assessment',
        slideOrder: 7,
        title: 'Assessment Methods',
        content:
          'Formative Assessment:\n- Padlet concept map contributions (timestamped)\n- Mentimeter quiz responses (anonymized)\n- Peer teaching observation checklist\n\nSummative Assessment:\n- Group Presentation: 15-min podcast critiquing HK curriculum\n  Rubric: Policy Analysis 40% | Practical Application 30% | Creativity 30%\n- Individual Essay: 800-word policy adaptation\n  Rubric: Critical Thinking 50% | Contextualization 30% | Referencing 20%',
        slideType: 'assessment',
        backgroundColor: null,
      },
      {
        storageKey: 'slide:alignment',
        slideOrder: 8,
        title: 'Constructive Alignment Matrix',
        content:
          'Learning Outcome → Teaching Activity → Assessment\n\nAnalyze curriculum components → Jigsaw Groups → Podcast Presentation\n\nEvaluate pedagogical strategies → Case Study Problem-Solving → Adaptation Essay\n\nAdapt standards to diverse contexts → Peer Teaching Feedback → Concept Map Mapping',
        slideType: 'content',
        backgroundColor: null,
      },
      {
        storageKey: 'slide:resources',
        slideOrder: 9,
        title: 'Resources & Differentiation',
        content:
          'Software: Mentimeter, Padlet, Canva, Google Jamboard\nPhysical: Printed HKEB curriculum excerpts\nDigital: EdCity sandbox, HKDSE past papers (2019-2023)\n\nDifferentiation:\n- Advanced: Compare HK with Singapore\'s Mother Tongue Framework\n- Visual: Color-coded curriculum diagrams\n- Multilingual: Simplified Chinese annotations\n- Accessibility: WCAG 2.1 compliant Padlet templates',
        slideType: 'content',
        backgroundColor: null,
      },
      {
        storageKey: 'slide:reflection',
        slideOrder: 10,
        title: 'Reflection & Next Steps',
        content:
          'Success Indicators:\n80% post-test score improvement over pre-test\nHigh Padlet participation rates\n\nFeedback:\nGoogle Form reflection survey\nOpen-response questions\n\nNext Session:\nDifferentiated instruction within curriculum constraints\n\nMaterial Generation:\n- Concept Map: HK Curriculum Components\n- Case Study: Budget Constraints in Sham Shui Po Schools\n- Podcast Rubric Template',
        slideType: 'content',
        backgroundColor: null,
      },
    ]);

    // ---- Mark v2 seed as applied ----
    await tx.insert(schema.seedLog).values({
      seedVersion: V2_SEED_VERSION,
    });
  });

  console.log(`Seed "${V2_SEED_VERSION}" applied successfully.`);
}

// --- Main seed runner ---
async function seed() {
  const client = postgres(process.env.DATABASE_URL!);
  const db = drizzle(client, { schema });

  try {
    await ensureSeedLogTable(db);

    // Run seeds in order
    await seedV1(db);
    await seedV2(db);
  } catch (error) {
    console.error('Seeding failed:', error);
    throw error;
  } finally {
    await client.end();
  }
}

seed()
  .then(() => process.exit(0))
  .catch(() => process.exit(1));
